Anim
gap-packages/simplicial-surfaces pull request #193
Opened 2022-02-07 18:20 UTC by ReymondAkpanya

The functions in the chapter "Animating surfaces with java script" do not longer require that the simplicial surfaces used as input have vertices, edges and faces given by the set [1..n].

2022-02-22 14:55 UTC, MeikeWeiss requested changes
Looks good!

2022-02-22 14:55 UTC, MeikeWeiss commented on gap/PolygonalComplexes/animating.gd
> +#! Get the transparency of the face <A>face</A>. If no transparency is set, the function returns 1. Otherwise the function returns the transparency value of the face <A>i</A>. (For more information l
Here it should be also face and not i

2022-02-22 14:55 UTC, MeikeWeiss commented on gap/PolygonalComplexes/animating.gi
> +    "for a simplicial surface, a face and a record",
Can you change in the method also index to face?

2022-04-08 13:08 UTC, MeikeWeiss approved these changes

2022-04-08 13:08 UTC, TomGoertzen approved these changes

2022-04-08 17:35 UTC, merged